### ISSUE TITLE
Add fork() methods to implement state copying

### ISSUE THREAD

**Issue by black-binary** [JonathanSalwan/Triton#1012]
Related issue: #532 

I found that the copy constructors of most classes are just simply copying the shared_ptr members. So I think we need an explicit method to deep copy an object (and deep copy all members of it). My suggestion is to add fork() methods (or deepCopy()?) to everything that needs to be deep copied, including:

- API
- TaintEngine
- SymbolicEngine, SymbolicExpression, SymbolicVariable
- CpuInterface
- AstContext, AbstractNode
- PathManager, PathConstraint
..

And when we want to fork a state, we just need to write

```c++
API state = ...;
...
API new_state  = state.fork();
```

Is this a good idea or a bad idea? Will there be some difficulties in implementing these methods? :)

**Comment by black-binary** [comment]
If you guys like it, I'd like to trying to implement it in the next few weeks and make a PR.

**Comment by JonathanSalwan** [comment]
Hey,

I've tried this one several months ago but can't remember the main problem with this. Anyway, it's something for sure that could be interesting to add to this project :).

The idea could be to improve/add C++ constructor by copy for every object. So that we can do at the end `API b = API(a)`. Note that for ASTs a deepcopy is necessary.

**Comment by SweetVishnya** [comment]
In ideal world symbolic expressions prefix should be shared with fork. Thus, we can fork fast and reduce memory consumption.

**Comment by JonathanSalwan** [comment]
It depend of the purpose of the fork. e.g: for a BFS or for a backup.

**Comment by JonathanSalwan** [comment]
I link this issue to #532.
