### ISSUE TITLE
Analyzing a Coredump file with Triton

### ISSUE THREAD

**Issue by edi33416** [JonathanSalwan/Triton#1026]
I'm trying to run Triton to do a taint analysis on a binary.
Based on the discussion in the issue #995 I wrote a small sample that attempts to emulate a simple program.

Doing so, I've hit the following issue: at some point, the code tries to access uninitialized library data;
some libraries, such as `libc` perform an initialization phase, either through the `.init` hooks, or other means.
As one can see, `libc`s initialization is pretty convoluted: https://www.gnu.org/software/hurd/glibc/startup.html

This got me wondering if I could use `gdb` to `break` at `main`s entry, dump a core file, and then load and emulate the instructions from the coredump.
In theory, the coredump will contain the process image after all the libraries have been loaded and initialized.

The [lief documentation](https://lief.quarkslab.com/doc/latest/tutorials/12_elf_coredump.html#final-word) implies that this should indeed be possible
> One advantage of the coredump over the raw binary is that relocations and dependencies are resolved inside the coredump.
> This API could be used in association with other tools. For instance, we could use Triton [...]

So this brings me here: I would like to load a coredump file and then execute the instructions with Triton, but I don't know how to do it. Simply parsing the coredump file with lief doesn't work, as the entrypoint is `0`
```
core = lief.parse("coredump")
print(hex(core.entrypoint)) -> 0
```

How would one go about to do such a task?

Thank you in advance,
Eduard

**Comment by JonathanSalwan** [comment]
> This got me wondering if I could use gdb to break at mains entry, dump a core file, and then load and emulate the instructions from the coredump. In theory, the coredump will contain the process image after all the libraries have been loaded and initialized.

Yes you can do that. Do not forget to use `BIND_NOW=1` when running your target so that the plt/got are initialized at the beginning. Regarding the dump, I've never tried with a real cordump but you can build your own one. Take a look at this [example](https://github.com/JonathanSalwan/Triton/tree/master/src/examples/python/ctf-writeups/defcon-2016-baby-re).

I'm using peda gdb and added [a patch](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/gdb-peda-fulldump.patch) to add a `fulldump` command. Then, you can break wherever you want and execute the `fulldump` command when the breakpoint is hit. Once it's done you have a custom [coredump](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/baby-re.dump). Then, in your triton tool, you only have to parse your own coredump and [load](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/solve.py#L78-L122) it to triton.

Hope it can help,

**Comment by edi33416** [comment]
> [...]
> I'm using peda gdb and added [a patch](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/gdb-peda-fulldump.patch) to add a `fulldump` command. Then, you can break wherever you want and execute the `fulldump` command when the breakpoint is hit. Once it's done you have a custom [coredump](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/baby-re.dump). Then, in your triton tool, you only have to parse your own coredump and [load](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/solve.py#L78-L122) it to triton.

First of all, thank you @JonathanSalwan for your help and quick response.

I've followed your example, but now I'm stuck at a different step.

I've added your patch to peda and used the `fulldump` command to create the dump and then I took your python load code to load the dump.
I have the following two issues:

1. The relocation is still done lazily, even with `export LD_BIND_NOW=1`
I've printed the `PC`, and this is what I get
```
[...]
[+] Memory caching 7ffffffde000-7ffffffff000
[+] Memory caching ffffffffff600000-ffffffffff601000
0x4d5106
0x4d510b
0x4d510d
0x4d5110
0x4d512b
0x4d5130
0x4d513a
0x4d513f
0x4d5141
0x401880
0x70
0x72
[...]
```
At the address `0x401880` I have a `call@plt`, as show below
```
 4d5141:  e8 3a c7 f2 ff         call   401880 <printf@plt>
```

This brings me to my 2nd issue

2. If the relocations were made,  would have expected to, at some point, reach a syscall: eg. `write` (through the `printf` call).
Until now, I would have found the relocation symbols with lief and pached the address to my python hooks, as per the #995 discussion. Now, how can I access the `binary.pltgot_relocations` and `dynamic_relocations`?

**Comment by JonathanSalwan** [comment]
1. I don't know what happen =/. Should be ok. Did you do the `LD_BIND_NOW` before the dump right?
2. Yes, if you go through libc functions at some points you have to support syscalls.
3. Take a look to [this example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/google2016-unbreakable/solve.py#L364-L388)
