### ISSUE TITLE
Thread switch in triton

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#1045]
Hi ,I'm using triton to simulating a multi-thread program.
Suppose I have two threads, the first thread has 2 instructions: "mov eax, 3" and "mov ebx, eax". the second thread only has one instruction "mov eax, 4". The two instructions are executed in the following order:
```
thread1: mov eax, 3
thread2: mov eax, 4
thread1: mov ebx, eax
```
After using triton to simulate the three instructions, I found that the `ebx` register is `4`, not `3`. 

But I think `ebx ` should be `3`, as it was assigned only in the first thread, and the instruction in the second thread should not affect it.
Is there anything wrong?

**Comment by SweetVishnya** [comment]
You should manually switch symbolic registers during a thread switch. Take a look at section VI.  https://arxiv.org/abs/2011.09269

**Comment by JonathanSalwan** [comment]
Hey,

How to do you handle thread processing with Triton? By calling setThreadId? This function is a bit misleading, this does not executes the instruction on a specific thread. Actually the core of Triton does not supports multi-threading by default. You have to do the scheduling of the execution by yourself and `setThreadId` allows you to define an `id` which will help you to schedule instructions.

However, I know it's possible to execute real multi-thread programs (I've managed to emulate a TCP/IP stack which use a lot of thread with success). If I got time I will push an example of simple multi-threading execution but the idea is:

1. Use only one `TritonContext`
2. Execute some instructions of a thread 1
3. Save the state of all registers in a class `thread.save(TritonContext)`
4. Execute some instructions of the thread 2
5. Save the state of all registers in a class and then restore the state of the thread 1 `thread.restore(TritonContext)`
6. Continue like that.

Thus, the shared memory is support by design and you only have to save and restore the registers state by thread. Note that you also have to support functions like mutex/semaphore/thread_create etc.

Hope it can help.

**Comment by JonathanSalwan** [comment]
[Here](https://github.com/JonathanSalwan/Triton/blob/dev-v0.9/src/examples/python/multi_threading.py) a little example of saving context when scheduling a thread.

**Comment by vancaho** [comment]
OK, thanks for your help.
