### ISSUE TITLE
Feature: multiple snapshots in python binding

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#116]
In python binding, there are takeSnapshot(), restoreSnapshot().
But what about returning 'dumpable' snapshot in takeSnapshot(), and using the dump of snapshot as first argument in restoreSnapshot()? (ex: sn = takeSnapshot(), restoreSnapshot(sn))

**Comment by JonathanSalwan** [comment]
Yep, it was the plan but not issue opened :P. We can't return a 'dumpable image' or snapshot when `takeSnapshot()` is called because when it is called, we can't predict what values or parts of memory will be modified during the execution. However, we can return an ID which represent an instance of snapshot. Then, when `restoreSnapshot(id)` is called, we restore the instance corresponding to the ID.

**Comment by Jinmo** [comment]
It sounds good. Thanks!

**Comment by JonathanSalwan** [comment]
Will not be implemented in the libtriton.
