### ISSUE TITLE
Store symbolic expressions to database and offload memory usage

### ISSUE THREAD

**Issue by hexpell** [JonathanSalwan/Triton#1169]
When processing trace with millions of instructions, memory quick used up for storing symbolic expressions. It's would be nice to have a feature to offload these expressions to an on-disk storage, like a database backend. It can also save processing progress so iterating analysis can reuse the saved data.

**Comment by JonathanSalwan** [comment]
You can use some modes:

```
setMode(ALIGNED_MEMORY, true)
setMode(CONSTANT_FOLDING, true)
setMode(ONLY_ON_SYMBOLIZED, true)
```

**Comment by hexpell** [comment]
Yes I'm already using these modes, but still, when there are hundreds of millions instructions to process, memory use can quickly goes out of control. An 8 hour run of 30 million instructions lead to over 100GB memory use.

**Comment by JonathanSalwan** [comment]
Yeah, everything depend on what you symbolize. More you symbolize more you will consume memory and on million instructions, you pay the cost on your memory. The max I did, is 300 million instructions but if I symbolize only what I'm looking for, I can keep my ram below  16 GB consumed. May I know what you are analyzing?

**Comment by hexpell** [comment]
Let me experiment more with the `ONLY_ON_SYMBOLIZED` mode first. I'm currently hitting some bug, not sure if it's my script or Triton, or my patches to Triton... Need to find some time to do debugging. But I will update here when I know more.

**Comment by JonathanSalwan** [comment]
> Having the symbolized expressions and concrete values stored in a DB will not only enable recoverable processing, and also the ability to run a lot of offline analysis without running the symbolization process all again. For example I can explore different slicing of the program respect to different origins without doing a full run of the symbolization process everytime.

I totally agree and I would love++ having this. I thought a lot about this feature but unfortunately I do not see a way to serialize and deserialize complexe C++ objects (shared_ptr, weak_ptr, unique_ptr, AST structure, etc.) on disk and then back to memory =(. If you have ideas to solve this issue feel free to discuss :)

> With the new symbolic memory model and those optimization modes you recommended above, its memory usage quickly goes above 200GB for less than 1M instructions processed in an hour. 

Yes, currently this is the main problem of using the ABV logic. This is due to our SSA form and the way of how we have to use `store` and `load` operators from the smt2lib. The `store` operator returns a new memory state, so our memory state is just a _recursive_ call to store operators like:

```
ref1 = store(mem_init, xxx, xxx)
ref2 = store(ref1, xxx, xxx)
ref3 = store(ref2, xxx, xxx)
ref4 = store(ref3, xxx, xxx)
ref5 = store(ref4, xxx, xxx)
...
``` 

The problem with this concept is that we have to keep all memory expressions and thus almost no expression is freed as no more used. I think in a first step we will finish the implement the array logic and then once it's pretty clear in our mind we can start thinking about how to optimize memory expressions.
