### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dhxkgozj** [JonathanSalwan/Triton#123]
<img src="http://blogfiles.naver.net/20150707_281/kdw8726_1436276885384ca7GQ_PNG/%C4%B8%C3%B31.PNG">

Error	3	error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXABVexception@std@@@Z)	C:\pintool2013\source\tools\MyPinTool\BaseIRBuilder.obj	MyPinTool
Error	6	error LNK2019: unresolved external symbol "__int64 __cdecl LEVEL_CORE::INS_OperandMemoryDisplacement(class LEVEL_CORE::INDEX<6>,unsigned int)" (?INS_OperandMemoryDisplacement@LEVEL_CORE@@YA_JV?$INDEX@$05@1@I@Z) referenced in function "class IRBuilder * __cdecl createIRBuilder(class LEVEL_CORE::INDEX<6>)" (?createIRBuilder@@YAPAVIRBuilder@@V?$INDEX@$05@LEVEL_CORE@@@Z)	C:\pintool2013\source\tools\MyPinTool\IRBuilderFactory.obj	MyPinTool

Link errors found in the windows porting.
can you this problem solve? or guesswork?

**Comment by JonathanSalwan** [comment]
MMmmh dunno :(. I never tried to compile a pintool on Windows :/

**Comment by Jinmo** [comment]
Well.. It seems like library problem. Did you add pin library path in the solution correctly?

**Comment by dhxkgozj** [comment]
@jinmo yes i do add all pin path.

**Comment by 0vercl0k** [comment]
I would recommend that you take a look at the VS solution "MyPinTool" Intel
includes in the examples. I know that every time I'm doing a pin tool on
Windows I copy this project (because they defined extra macros, special
options, etc) with
https://github.com/0vercl0k/stuffz/blob/master/setup_pintool_project.py.

Cheers,
0vercl0k

2015-07-12 6:11 GMT-07:00 TAKI <notifications@github.com>:
