### ISSUE TITLE
Why i stuck at idiv instruction

### ISSUE THREAD

**Issue by AnduinBrian** [JonathanSalwan/Triton#1260]
Hello, im writing a script to detect opaque predicate. I use this [sample and script](https://github.com/JonathanSalwan/X-Tunnel-Opaque-Predicates) but dont recieved anything. When i try to write it myself, i notice i was stucked at the idiv instruction. Here is a detail look:
In IDA, i got this block:
![image](https://github.com/JonathanSalwan/Triton/assets/36282595/20f4e109-a6e8-4f85-b617-f19c2c030f88)

My script will process every instruction in this block and print out instruction Disassembly. But the result i got show me that my script wont pass through the idiv, it just stay there:
![image](https://github.com/JonathanSalwan/Triton/assets/36282595/3f8c3e4a-9c99-40bb-8ce9-adc1e49ace3a)

my script:
```
from idautils   import *
from idaapi     import *
from idc        import *
from triton     import *

def prove_bb(startEA, endEA):
    global ctx
    global names
    global nb_ed
    global nb_in
    global nb_to

    ctx = TritonContext()
    ctx.setArchitecture(ARCH.X86)
    ctx.setMode(MODE.ALIGNED_MEMORY, True)

    names = dict()

    # Symbolize registers
    for r in ctx.getParentRegisters():
        var = ctx.symbolizeRegister(r)
        names.update({var.getName() : str(r)})

    ip = startEA
    for _ in range(1000):
        # Get opcodes from IDA and exectue them into Triton
        inst = Instruction()
        opcode = idc.get_bytes(ip, 16)
        inst.setOpcode(opcode)
        inst.setAddress(ip)
        ctx.processing(inst)

        print(hex(inst.getAddress()), inst.getDisassembly())

        # Get next instruction
        ip = ctx.getSymbolicRegisterValue(ctx.registers.eip)


prove_bb(0x407BE2, 0x407C0C)
```
Why is this happend and how can i fix this. Thanks
Best Regards,

**Comment by JonathanSalwan** [comment]
Hey,

Probably because the `idiv` instruction raised an exception. `processing` can return these following exception enums:

* `EXCEPTION.NO_FAULT`: No fault, execution succeed.
* `EXCEPTION.FAULT_DE`: Fault raised: Divide-by-zero.
* `EXCEPTION.FAULT_BP`: Fault raised: Breakpoint.
* `EXCEPTION.FAULT_UD`: Fault raised: Instruction not supported.
* `EXCEPTION.FAULT_GP`: Fault raised: General Protection Fault.

Maybe you got `EXCEPTION.FAULT_DE`. In this case, the program counter is not incremented and you loop on the same instruction.

Two solutions:

1) If you got an exception, just ignore it and increment the program counter yourself. (e.g `ip = inst.getNextAddress()`)
2) define an initial context that will not raise a div by zero exception.

**Comment by AnduinBrian** [comment]
maybe div by zero. I think so
