### ISSUE TITLE
[friendly reminder] LLVM version > 16 wont work when building triton

### ISSUE THREAD

**Issue by vxcall** [JonathanSalwan/Triton#1340]
## problem and proposal
When i built with latest LLVM, this error showed up saying `llvm/Transforms/IPO/PassManagerBuilder.h` is not found.

```Shell
C:\Users\pseuxide\works\Triton\src\libtriton\includes\triton\tritonToLLVM.hpp(24,10): error C1083: Cannot open include
file: 'llvm/Transforms/IPO/PassManagerBuilder.h': No such file or directory [C:\Users\pseuxide\works\Triton\build\src\l
ibtriton\triton.vcxproj]
```

indeed, seems llvm deleted the header file any versions later than 16. so I think the LLVM has to be below 16 when building triton.

So README's under Install section should be

```Shell
* llvm          (optional)   >= 12
↓
* llvm          (optional)   12 <= llvm <= 16 # this might look odd?
```

anyways, so I thought it would be better to have some warning or annotation about it for noobs like me!

## out of scope, but
Even without this problem, building triton on Windows is pretty complicated for beginners. Having more step by step document in readme would be helpful. It was too complicated so [I made it by myself for me tho.](https://gist.github.com/vxcall/5e37b8c2adcdf2c42ddbbb1d5442c868)

**Comment by vxcall** [comment]
Also can you kindly let me know which dll do I have to put in python's site-package folder for LLVM?

**Comment by JonathanSalwan** [comment]
I'm not really experienced compiling things on Windows. Regarding LLVM on Windows I suggest pinging @mrexodia who has great experience on this stuff :)

**Comment by vxcall** [comment]
@JonathanSalwan @mrexodia 
Let me change my question, is LLVM linked statically or dynamically?
I tried to read it from cmake file but didnt understand how it handles about LLVM link.

I mistakenly closed the issue sorry

**Comment by mrexodia** [comment]
On Windows you build LLVM like this:

```
git clone -b release/15.x --single-branch https://github.com/llvm/llvm-project.git
cd llvm-project

# build LLVM with custom installation directory
cmake -S llvm -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_PARALLEL_LINK_JOBS=1
cmake --build build
cmake --install build --prefix "%USERPROFILE%/lib/my-llvm-15"
```

Then you need to pass the generated prefix to the Triton CMake invocation:

```
cmake -B build -DCMAKE_PREFIX_PATH:FILEPATH=%USERPROFILE%/lib/my-llvm-15
```

Per default LLVM links as a fully static library, but with a dynamic CRT (/MD).

It's been a while since I built Triton on Windows though, but as a general pattern CMake uses your CMAKE_PREFIX_PATH when doing `find_package` so you can do the same steps for other dependencies (capstone, z3, etc). There is a CMake pattern called 'superbuild' that I have an example of here: https://github.com/mrexodia/cxx-common-cmake. It also has some explanations, but essentially you have 2 stages of your project:

1. Build the `dependencies` folder (which uses `ExternalProject_Add` for all dependencies) so that you get a prefix in `dependencies/build/install`
2. Build the main project pointing `CMAKE_PREFIX_PATH` to `dependencies/build/install`

The tricky part is packaging all your dependencies in CMake correctly so that this pattern works, but popular projects like LLVM/z3/capstone do this.

**Comment by vxcall** [comment]
@mrexodia
Thanks mrexodia!
So it's statically linked! (runtime lib is dynamic)
I successfully built Triton with LLVM but wasn't sure if i need to extract any of the produced .dll file, so thanks!

> There is a CMake pattern called 'superbuild'

I didnt know it has a name, first time saw it so the explanation was helpful!

> The tricky part is packaging all your dependencies in CMake correctly so that this pattern works

I see I see...

Thanks for the informative response again, glad I got proper answer from one of the best reverse engineer in this era!
@JonathanSalwan thanks for escalating too man!
