### ISSUE TITLE
How about removing taint engine?

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#153]
Well.. Triton has IR, and SMT based symbolic execution engine, but I'm wondering why taint engine exists.
Because taint engine provides tainted execution based on some data transfer operations, and some cases like (xor eax, eax), I think it can't be exact result of taint.
So, how about removing taint and merge it to symboli execution engine? (like symbol.isTainted == True)

**Comment by JonathanSalwan** [comment]
Taint analysis and symbolic execution are two different things. Inside Triton, taint analysis is useful for two main cases:

* First, when I open IDA, I like when I directly see what instructions are controlled by the user input. You can do that by generating a database with [this tool](https://github.com/JonathanSalwan/Triton/blob/master/tools/generate_db.py) and use a custom IDA plugin.

* Then, the main objective of the taint engine inside Triton is to determine at each program point if we can ask a model to the solver. In fact, ask a model at each program point to know if we can influence the path condition or the register/memory value is really expensive. So we only ask a model if we know that the instruction may be controllable by the user - it means that the symbolic expression contains symbolic variable(s). Otherwise, if the instruction is not tagged as tainted, it means that the symbolic expression can be replaced by a constant because nothing can influence the formula.

Finally, in specific cases, we want to setup a symbolic variable without using the taint analyzer. So, that's why the symbolic engine and the taint engine are separated. In the long term, Triton will be a framework of program analysis not only a symbolic engine. So, we would like to separate all engines of each others.

> So, how about removing taint and merge it to symboli execution engine? (like symbol.isTainted == True)

Actually, it's already like [that](https://github.com/JonathanSalwan/Triton/wiki/Class_SymbolicExpression). :)

**Comment by cheesechoi** [comment]
I was wondering that too :)
