### ISSUE TITLE
Exponential size in Symbolic expresions

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#204]
Hi, 

While I was doing some tests with the code coverage tool, I detected that in some cases the symbolic expressions were growing very fast.

The following code is an example triggering this behavior:
```
#include <stdio.h>

int main(int argc, const char **argv)
{
    int n = 0;
    n++;
    n++;
    n++;
    n++;
    n++;
    n++;
    n++;
    n++;
    if (n == 8)
        printf("8\n");
    return 0;
}

```

The ZF in the condition `n ==8` has a symbolic expression very big, of 3.670.032 nodes.

This happens because each time the variable is accessed are created 4 new references (one per byte), and each one is keeping all the previous tree.

I don't know how to solve it. Maybe doing some kind of optimization? (detecting when is accessed a DWORD and joining all the values....) Or maybe it is possible to use some kind of construction in smtlib to group the same nodes tree.

**Comment by romainthomas** [comment]
> Maybe doing some kind of optimization?

We are working on an AST simplifier and we have good results on the simplified AST's size. 

> Or maybe it is possible to use some kind of construction in smtlib to group the same nodes tree.

In fact in the AST we use reference. For instance if we have 
```
xor eax, eax
```
It will be stored as:
```
(bvxor #1 #1)
```

Where `#1` is a reference to the `eax` expression. When we do a `getFullExpression` we break the references.  
There is also this [paper](http://www.eecs.berkeley.edu/Pubs/TechRpts/2014/EECS-2014-173.pdf) which explains  how to reduce variables in symbolic execution. It should be implemented in the `v0.3`

**Comment by JonathanSalwan** [comment]
@0ca you're right about exponential size in symbolic expressions when there is LOAD/STORE.

In fact, as the memory can be accessed on unaligned address we have to keep a symbolic expression for each byte of memory.

Example:

`mov dword ptr [mem], eax`

Each byte of the memory pointer will be assigned with the appropriated `(extract x y)` of the eax's expressions. This is very important because when we have something like this:

`mov dl, byte ptr [mem+1]`

We know which symbolic expression has been referenced to `mem+1`.

Now, the worst case is when we have something like this:

```
(a) mov qword ptr [mem], rax
[...]
(b) mov rdx, qword ptr [mem]
```

In this case, we have at `(a)` 8 `extract x y` references and at `(b)` 8 `concat` of `extract x y` references.

To optimize this, we can detect the LOAD/STORE's size and merge the appropriated nodes.

As @romainthomas said, we are working on an AST simplifier and this kind of simplification should be possible.

**PS**: Please note that as we used [SMT reference node](http://triton.quarkslab.com/documentation/smt2lib-representation/#ast-representation) to optimize memory consumption, the replicated nodes are not reallocated in memory but referenced which should not affect your RAM consumption.

**Comment by JonathanSalwan** [comment]
Hey @0ca,

Take a look to this [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/symbolic_emulation_crackme_xor.py) and the **concat** rule. You can try to run the script without the simplification to see the difference.

**Comment by JonathanSalwan** [comment]
Fixed. Please use:

```python
enableSymbolicOptimization(OPTIMIZATION.ALIGNED_MEMORY)
```
