### ISSUE TITLE
symbolicEmulation vs. concolic execution

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#284]
The doc says:

> `enableSymbolicEmulation(bool flag)`
Enables or disables the symbolic emulation. Set true for a full symbolic execution (emulation) or false for a concolic execution.

I don't really understand what the term 'full symbolic execution' is supposed to mean in the Triton context. Does it mean every register and memory cell is symbolic by default? So no more need to explicitly call `convertMemoryToSymbolicVariable()` or `convertRegisterToSymbolicVariable()`?

(My experiments let me think this is wrong, as my code did not work without explicitly defining symbolic variables.)

If I still need to define symbolic variables in emulation mode, what is the difference to the normal mode? I mean, in both modes you call `processing(inst)`, and in both modes you have access to the smt formulas, and in both modes you need to define your symbolic variables, and in both modes can query a model.

The normal mode is what you call 'concolic execution', right?

How would the examples 
http://triton.quarkslab.com/documentation/doxygen/Tracer_page.html
and
https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/symbolic_emulation_crackme_xor.py
look different if they were not in 'emulation mode' but in 'concolic mode'?
Would the 'concolic mode' have limitations given these examples?

**Comment by JonathanSalwan** [comment]
Hey,

Well, it's a good question and I will try to explain the Triton's philosophy about all of this.

I know that the term **symbolic execution** is the fact to use symbolic variables instead of concrete values and a **concolic execution** is the fact to use both.

To perform a symbolic or a concolic execution we must keep the data and the control flow of each program point. Data and control flow are represented by SMT2-Lib  formulas. 

Triton can build these formulas in two different ways:

* **Full emulation**: The registers and memory state are evaluated from SMT formulas. The bad point is that it's very slow due to the evaluation of SMT formulas to spread values and the fact that we need all semantics to fully execute the code (like any emulator). The good point is that all values assignment are on SSA form and that we can perform a symbolic execution at any point.

* **Concrete support**: The second way is to rely on a tracer (e.g: DBI) to synchronize the memory and the registers state from the real CPU context. The bad point is that we must use a tracer and start the analysis at the program entry point. The good point is that it's really fast and there is no desynchronization between our formulas and the real CPU context.

> I mean, in both modes you call processing(inst), and in both modes you have access to the smt
> formulas, and in both modes you need to define your symbolic variables, and in both modes can
> query a model.

Yes, these both modes are just two different ways to build formulas and the only difference between the **full emulation** and the **concrete support** is that for the **concrete support** you must give the CPU context at each program point via:

* `inst.updateContext(Memory(...))`
* `inst.updateContext(Register(...))`

While the **full emulation** will **try to predict** the current CPU state by computing the last formulas. As you can see with this [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/symbolic_emulation_crackme_xor.py), the `serial` function is fully executed without giving any CPU context.

To conclude, both modes in Triton allows the user to do same things (setup symbolic variables, define constraints, get models, etc), the only difference is how these modes built formulas.
