### ISSUE TITLE
iterating over all registers (cpuNumberOfReg() != len(REG.__dict__)

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#322]
I wanted to iterate over all registers and notices that the return value of

`triton.cpuNumberOfReg()`` # returns 99`

differed from

`len(REG.__dict__)  # not counting the __doc__ and __module__ one gets 98

Is this a bug?

**Comment by JonathanSalwan** [comment]
> Is this a bug?

Mmmh, not really. It seems that the `cpuNumberOfReg()` returns the number of registers contained inside the enum register (including the `INVALID_REG`) and the namespace `REG` export all registers expect the `INVALID_REG`. That's why there is a difference of 1. We will export the INVALID_REG into the namespace `REG` to avoid any confusion :)

**Comment by JonathanSalwan** [comment]
btw, if you want to iterate on all registers or parent registers use:

* getAllRegisters()
* getParentRegisters()

**Comment by gitttt** [comment]
Ah, all the better. I did not had the latest version, and did not see it.
Thanks for the hint!
