### ISSUE TITLE
/usr/bin/ld: cannot find -lpindwarf

### ISSUE THREAD

**Issue by techvoltage** [JonathanSalwan/Triton#331]
Hi, while using build instructions on http://triton.quarkslab.com/documentation/doxygen/#install_sec
I get error in make command

/usr/bin/ld: cannot find -lpindwarf

**Comment by JonathanSalwan** [comment]
Did you used pin-3 ? If yes, use pin-2.

**Comment by invisibleexploits** [comment]
I can confirm this, I encountered the same issue when installing pin 3.0.
After retrying with pin 2.0. it worked :)

**Comment by JonathanSalwan** [comment]
If you want to use the tracer shipped with the Triton project, you **must** use the version 2 (71313) of Pin because we will never move on the version 3.0. The reason is that Pin 3.0 does not allows to compile pintools with external libraries (even with the C++ standard). Since the v3.0, the Pin team forces their users to use their PinCRT library which is clearly not reliable/usable at this moment.
