### ISSUE TITLE
triton::exceptions namespace

### ISSUE THREAD

**Issue by illera88** [JonathanSalwan/Triton#344]
Right now Triton is blindly trusting Capstone to disassemble a set of opcodes or raising an exception otherwise not letting the users control not expected situations and leading to a crash.

Triton should know that capstone failed and pass the error info to the user so he can control the situation:
https://github.com/JonathanSalwan/Triton/blob/35f066679f619259a465580c9e5e00809e7390c4/src/libtriton/arch/x86/x86Cpu.cpp#L568

Instead of raising an exception terminating the program. (https://github.com/JonathanSalwan/Triton/blob/35f066679f619259a465580c9e5e00809e7390c4/src/libtriton/arch/x86/x86Cpu.cpp#L647)

This behavior should be similar than the one that occurs when Triton can't create a SSE for a given instruction (Triton doesn't crash because of that).

Cheers

**Comment by JonathanSalwan** [comment]
Hey,

Sorry for the delay. After thinking about it I will not return a value if capstone cannot disassemble correctly an instruction. In the libTriton's API, we use exceptions to catch and manage critical behaviors and we think this is the good way to handle critical errors.

However! I agree that our exceptions system are not yet very well managed. For example, in this case, we should raise a `triton::exception::disassemblyError` instead of a `std::runtime_error`.

So, I suggest to develop a real exceptions namespace to catch specific errors. Then, we can imagine some callbacks (#318) to catch specific exceptions.

Cheers,

**Comment by JonathanSalwan** [comment]
Currently in `dev-next`
