### ISSUE TITLE
Deal with pathPredicate

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#350]
- ~pathManager.popPathConstraint()~
- ~pathManager.pushPathConstraint()~
- ~pathManager.clearPathConstraints()~
- ~pathManager.getPathConstraints()~
*Returns all constraints of taken and not taken branches.*
- ~pathManager.getPathPredicate()~
*Returns the path predicate as an AST of logical conjunction of each taken branch.*
- ~pathManager.getPredicatesToReachAddress(integer addr)~

**Comment by RobinDavid** [comment]
Working with path constraints. There is apparently no way to link a constraints to the instruction that generated it. As such we cannot easily get the path constraint prefix up to a given instruction. Let me explain the issue in the context of trace execution where every instruction have a unique id:

    1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> 8 -> 9 -> 10

Some of them will yield constraints in the path predicate because they are conditional jump or whatsoever like:

      ->   ->  -> Cst  ->   ->   ->  Cst ->   ->

As of now there is no (easy) way to get the path predicate prefix up to the instruction 6 (for instance).

It can reasonably easily be implemented by creating a unique id to each Instruction() instance and to associate this id to all constraints added at that instruction.

Let me know if that makes sense for you :wink: 

_(that would probably require a specific issue)_
