### ISSUE TITLE
Is it possible to get the address the the branch belonging to a pathcontstraint?

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#358]
Something like that:

```
path_constraints = getPathConstraints()
for pc in path_constraints:
    branches = pc.getBranchConstraints()
    for b in branches:
        print "0x%x" % b.address
```

The doc says we can get the taken target of a branch via 

> getTakenAddress(void)
> Returns the address of the taken branch as integer.

What about the location where this branch is (e.g. the location of the `jne`)?
Does this even make sense?

**Comment by JonathanSalwan** [comment]
```python 
path_constraints = getPathConstraints()
for pc in path_constraints:
    branches = pc.getBranchConstraints()
    for b in branches:
        print "0x%x" % b['target']
```

**Comment by gitttt** [comment]
Isn't `b['target']` the target address of the branch, but not the location of the jump, right?

In other words, given

`0xdeadbeef: jne 0xcafebabe`

`b['target']` is 0xcafebabe, right?

Is it possible to get 0xdeadbeef ?

**Comment by JonathanSalwan** [comment]
> Is it possible to get 0xdeadbeef ?

`instruction.getAddress()`

**Comment by JonathanSalwan** [comment]
You can deal with:

* `b['target']`
* `instruction.getAddress()`
* `instruction.getNextAddress()`

**Comment by JonathanSalwan** [comment]
Ok I got your point. Currently it's not possible. Let my few days to add `b['address']` which corresponds to `instruction.getAddress()`.

**Comment by gitttt** [comment]
okay, excellent. Take your time. Pas de stress! :-)

**Comment by JonathanSalwan** [comment]
* **getBranchConstraints(void)**<br>
Returns the branch constraints as list of dictionary {isTaken, srcAddr, dstAddr, constraint}. The source address is the location of the branch instruction and the destination address is the destination of the jump. E.g: "0x11223344: jne 0x55667788", 0x11223344 is the source address and 0x55667788 is the destination if and only if the branch is taken, otherwise the destination is the next instruction address.
