### ISSUE TITLE
SymbolicEngine copy constructor is not copying the whole object

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#385]
Hi, 

I was trying to use the Snapshot engine from PIN in another project. And at some point I wanted to copy the symbolicEngine to have a copy of the engine in one status and be able to restore in the future.

And I found an issue reseting the symbolic engine after I deleted the copy. The next C++ code reproduces the behavior:
```
	triton::api.setArchitecture(triton::arch::ARCH_X86);
	triton::api.convertMemoryToSymbolicVariable(triton::arch::MemoryAccess(0x401000, 1, 0), "");
	auto symbolic_engine_copy = new triton::engines::symbolic::SymbolicEngine(*triton::api.getSymbolicEngine());
	delete symbolic_engine_copy;
	triton::api.resetEngines();  <---This crashes deleting the symbolic engine
```

I guess the problem is the copy is not complete and there is some attribute from that class that is use in both engines, the original one and the copy. So when I do resetEngines I am having a double free.

Is that correct? Is it possible to fix it? I checked the code but I am not sure where it is the problem.

Thank you for your time!

**Comment by 0ca** [comment]
And related with this, why in the PIN tracer you don't delete the old symbolic engine after a restart?
https://github.com/JonathanSalwan/Triton/blob/master/src/tracer/pin/snapshot.cpp#L125

I guess something like this would be "more" correct:
```
//Removing the current engine
delete triton::api.getSymbolicEngine();
//Restoring the old one
*triton::api.getSymbolicEngine() = *this->snapshotSymEngine;
```

**Comment by JonathanSalwan** [comment]
Hey,

It's an interesting thread because you are wrong and right at the same time :).

> I guess the problem is the copy is not complete and there is some attribute
> from that class that is use in both engines, the original one and the copy. So
> when I do resetEngines I am having a double free.
> Is that correct?

Yes

> Is it possible to fix it?

That's the interesting part. Yes I may fix this bug but I will not because I need this behaviour - I don't want to duplicate the whole objects.

Indeed, when you copy the object `SymbolicEngine`, I don't perform a deep copy to duplicate all `SymbolicExpression`, `SymbolicVariable` and `AbstractNode` objects. That's why when you delete your copy of the symbolic engine and then call the `resetEngines` function, there is a double free bug - `SymbolicExpression` and `SymbolicVariable` are deleted twice.

In several cases I need to do backups and to restore them very quickly. So, I don't want to spend lot of time in the object copy processing. Let's assume that you do a backup at a point A and then restore this backup at a point B. The point A is a subset of the point B, right? It means that everything in A is also contained in B. Based on this behaviour, why copying all objects twice whereas we can only  restore the state of the point A and deleting only the difference between these points (from B to A).

That's exactly what we are doing in the Pin's stuff you linked previously. We deleting all differences between a point B to A [[1](https://github.com/JonathanSalwan/Triton/blob/5d25cf6ebf81fbbafb3a6c9ad3ec70c9244a6d9e/src/tracer/pin/snapshot.cpp#L104), [2](https://github.com/JonathanSalwan/Triton/blob/5d25cf6ebf81fbbafb3a6c9ad3ec70c9244a6d9e/src/tracer/pin/snapshot.cpp#L114)] and we restore the original symbolic state [[3](https://github.com/JonathanSalwan/Triton/blob/5d25cf6ebf81fbbafb3a6c9ad3ec70c9244a6d9e/src/tracer/pin/snapshot.cpp#L124)]. Here, there is no memory leak.

In your case, I recommend to not deleting your copy.

**However (1)!** I agree that we should move [[1](https://github.com/JonathanSalwan/Triton/blob/5d25cf6ebf81fbbafb3a6c9ad3ec70c9244a6d9e/src/tracer/pin/snapshot.cpp#L104), [2](https://github.com/JonathanSalwan/Triton/blob/5d25cf6ebf81fbbafb3a6c9ad3ec70c9244a6d9e/src/tracer/pin/snapshot.cpp#L114)] into our `triton::api.restoreSymbolicEngine()` function instead of the pintool. Otherwise there is a memory leak if you direcly use the C++ API.

**However (2)!** I think you indirectly find a bug which triggers the double free using:

```python
import sys

from triton import *

if __name__ == "__main__":
    setArchitecture(ARCH.X86_64)

    inst = Instruction()
    inst.setOpcodes("\x48\x01\xD8")
    processing(inst)

    enableSymbolicEngine(False) # This call triton::api.backupSymbolicEngine() at each instruction processing.

    inst = Instruction()
    inst.setOpcodes("\x48\x01\xD8")
    processing(inst)

    resetEngines() # double free

    sys.exit(0)
```

**Comment by 0ca** [comment]
Thank you so much!

**Comment by JonathanSalwan** [comment]
Should be good now.
