### ISSUE TITLE
using Trition with a tracer: setConcreteMemoryValue and desynchronization 

### ISSUE THREAD

**Issue by jstij** [JonathanSalwan/Triton#418]
In your documentation you have an example demonstrating how Triton's API can be used to build the semantics of each instruction stored in a fictive database:
> http://triton.quarkslab.com/documentation/doxygen/Tracer_page.html

   ```
64        # Update concrete memory access
   65         accesses = db.get_memory_access_from_inst_id(inst_id)
   66 
   67         # Update memory access
   68         for access in accesses:
   69             if access['kind'] == 'R':
   70                 address = access['addr']
   71                 data    = access['data']
   72                 value   = struct.unpack(unpack_size[len(data)], data)[0]
   73                 setConcreteMemoryValue(MemoryAccess(address, len(data), value))
   74 
   75         # Process everything (build IR, spread taint, perform simplification, ...)
```
Yet, the documentation says:
> **setConcreteMemoryValue(MemoryAccess mem)**
Sets the concrete value of a memory cell. Note that by setting a concrete value will probably imply a desynchronization with the symbolic state (if it exists). You should probably use the `concretize` functions after this.

My question:
What if there is a symbolic value at a memory address? If we call `setConcreteMemoryValue()`, the memory value will be no more symoblic. If we call `processing(inst)` afterwards, like it is done in the above mentioned example code, we would not have the correct symbolic state any more, right?

What is the suggested solution here? Never calling `setConcreteMemoryValue()`? But how does Triton know what value is at this address then? Using (the outdated and removed) `enableSymbolicEmulation()` would have worked without any `setConcreteMemoryValue()`, right?

I looked at issue 357 again:
"Now, the state between the symbolic value and the concrete value is synchronized at every program points. So, there is no need to define the a symbolic emulation flag." [ [issue 357](https://github.com/JonathanSalwan/Triton/issues/357) ]

And further

> "Note that if you update a concrete value and want to keep the synchronization with the symbolic state you still need to use the concretize functions (concretizeRegister() or concretizeMemory()) after or before setting this value to force the libTriton to use the concrete value at the next processing."

So, do I have to call `setConcreteMemoryValue()`and then `concretizeMemory()`? Does this update the symbolic state and the concrete state without having a "desynchronization" ? Why is this not done in the above mentioned example code?

**Comment by JonathanSalwan** [comment]
Hey,

If Triton fetches for the very first time a memory cell(s) or a register it will transforms the concrete value to a symbolic one (it there is no concrete value, it defines a symbolic value with 0x00). Otherwise, if Triton fetches a memory cell(s) or a registers for a second (or more) time, it uses the last symbolic value assigned (SSA-based form). That's why, setting a concrete value after the very first fetch has no impact to the symbolic engine and will imply desynchronization. That's also why if you want to define a concrete value you have to concretize the reg/mem to come back to the very first fetch scenario.

For a formal definition:

![2016-12-07-151340_1600x900_scrot](https://cloud.githubusercontent.com/assets/991046/20970907/c070568a-bc8f-11e6-8ba3-77cbc6946dc6.png)

**Comment by jstij** [comment]
What do you mean by 

> fetches for the very first time a memory cell

?
Do you mean calling `processing(inst)` the first time, where `inst `is an instruction that e.g. reads a memory location?

Or do you mean explicitly calling a Triton API function such as `getConcreteMemoryValue()` ?

What do you mean by 

> setting a concrete value after the very first fetch

?
Can you give an example how this very first fetch followed and the setting of a concrete value would look like in Python/Triton API code?

**Comment by JonathanSalwan** [comment]
> Do you mean calling processing(inst) , where instis an instruction that e.g. reads a memory location?

My bad. More precisely, if we load a memory cell which has already been stored symbolically, we use the symbolic expression instead of the concrete value.  

> Can you give an example how this very first fetch and the subsequent setting of a concrete value would look like in Python/Triton API code?

```assembly
1. mov al, [0x8000] ; Triton uses the concrete value at 0x8000
2. mov bl, [0x8001] ; Triton uses the concrete value at 0x8001
3. add bl, al
4. mov [0x8000], bl
5. mov dl, [0x8000] ; Triton uses the symbolic value at 0x8000
```

Line 1, if there is no concrete value defined, Triton will load 0x00 into `al`. Same for line 2. Line 4, we store the AST `bl + al` into the memory cell located at 0x8000. Line 5, this memory cell 0x8000 has been symbolized by `bl + al` so, we load this AST into `dl`.

In the case of the line 5, we use the symbolic value located 0x8000 because this memory cell has been symbolically stored by the line 4. So, if before the processing of the line 5 you define a new concrete value at 0x8000, when you will process the instruction, the new concrete value will not be taken into account. Example:

```assembly
; setConcreteMemoryValue(0x8000, 0x1)
; setConcreteMemoryValue(0x8001, 0x2)
1. mov al, [0x8000] ; Triton uses the concrete value (0x1) at 0x8000
2. mov bl, [0x8001] ; Triton uses the concrete value (0x2) at 0x8001
3. add bl, al
4. mov [0x8000], bl
; setConcreteMemoryValue(0x8000, 0x11)
5. mov dl, [0x8000] ; Triton still uses the symbolic value (bl + al) at 0x8000
```

Now let see what is going on if you use concretization:

```assembly
; setConcreteMemoryValue(0x8000, 0x1)
; setConcreteMemoryValue(0x8001, 0x2)
1. mov al, [0x8000] ; Triton uses the concrete value (0x1) at 0x8000
2. mov bl, [0x8001] ; Triton uses the concrete value (0x2) at 0x8001
3. add bl, al
4. mov [0x8000], bl
; concretizeMemory(0x8000)
; setConcreteMemoryValue(0x8000, 0x11)
5. mov dl, [0x8000] ; Triton uses the concrete value (0x11) at 0x8000
```

**Comment by jstij** [comment]
Thank you for the detailed clarifications!

Regarding the code from here http://triton.quarkslab.com/documentation/doxygen/Tracer_page.html

```
69             if access['kind'] == 'R':
70                 address = access['addr']
71                 data    = access['data']
72                 value   = struct.unpack(unpack_size[len(data)], data)[0]
73                 setConcreteMemoryValue(MemoryAccess(address, len(data), value))
```
how can we know that `address` is read the very first time? What if the value is read for the 2nd time during the execution and thus appears the 2nd time in the trace and thus we call `setConcreteMemoryValue()` for a 2nd time on exactly the same address `address`?

Do we need to take care that we set (via  `setConcreteMemoryValue()`) every memory location only once (e.g. in the beginning) and let the `processing` do the rest of the job? In case of the code on the Tracer_page.html, this is not the case though. There, `setConcreteMemoryValue(MemoryAccess(address, ...)` is called whenever address `address` is read, no matter if read for the first, second, or 10th time.

**Comment by JonathanSalwan** [comment]
You have two solutions:

1) Set all concrete memory area values and let processing do the rest of the job.
2) Only set concrete memory values when Triton need it, like below:

```python
69             if access['kind'] == 'R':
70                 address = access['addr']
71                 data    = access['data']
72                 value   = struct.unpack(unpack_size[len(data)], data)[0]
73                 setConcreteMemoryValue(MemoryAccess(address, len(data), value))
```

> In case of the code on the Tracer_page.html, this is not the case though. There, setConcreteMemoryValue(MemoryAccess(address, ...) is called whenever address address is read, no matter if read for the first, second, or 10th time.

Indeed and it works because of what I explained before:

```assembly
; setConcreteMemoryValue(0x8000, 0x1)
; setConcreteMemoryValue(0x8001, 0x2)
1. mov al, [0x8000] ; Triton uses the concrete value (0x1) at 0x8000
2. mov bl, [0x8001] ; Triton uses the concrete value (0x2) at 0x8001
3. add bl, al
4. mov [0x8000], bl
; setConcreteMemoryValue(0x8000, 0x11)
5. mov dl, [0x8000] ; Triton still uses the symbolic value (bl + al) at 0x8000
```

Checkout the line 5. We use twice `setConcreteMemoryValue` at 0x8000 but only the first one is taken into account. This design allows us plug any kind of tracers or database at any program point.

**Comment by jstij** [comment]
I think I got it. Thank you very much for your patience and your detailed answers!

**Comment by jstij** [comment]
One last question regarding the two options. Which one has a better performance? And why?

**Comment by JonathanSalwan** [comment]
> One last question regarding the two options. Which one has a better performance?

The second one.

> And why?

Because during an execution, the binary only uses few parts of its memory area. For example, it's useless to define 1GB of memory area while during the execution you will only need few MB.

**Comment by jstij** [comment]
Does the above also apply to `setConcreteRegisterValue` ?

**Comment by JonathanSalwan** [comment]
You use `setConcreteRegisterValue` only if there are already `SymbolicRegister` values defined. So if you define all memory area before processing anything, you don't need to use `setConcreteRegisterValue`.
