### ISSUE TITLE
ROL treats CF, OF as input

### ISSUE THREAD

**Issue by gyorokpeter** [JonathanSalwan/Triton#444]
What's the reason for this?

```python
>>> from triton import *
>>> setArchitecture(ARCH.X86)
>>> inst = Instruction('\xC1\xC1\x0E')
>>> processing(inst)
>>> inst
0: rol ecx, 0xe
True
>>> for reg in inst.getReadRegisters():
...     print reg[0].getName()
...
ecx
cf
cf
of
```

**Comment by JonathanSalwan** [comment]
Some outputs are assigned according to a specific input computation. E.g about the carry flag of `ROL`:

```
if (count & countmask != 0):
    cf <- LSB(DEST);
```

The problem is that, using our representation model, we cannot represent expressions over an if-only-if (`iff`) node. We must use an if-then-else (`ite`) node. Thus, the previous pseudo-code is represented as follow:

```
if (count & countmask != 0):
    cf ← LSB(DEST);
else:
    cf ← cf
```

That why, `ROL` and other instructions need undocumented specific registers. The fact is that `getReadRegisters()`, `getWrittenRegisters()`... are used to know what Triton needs and what Triton did. It's not a big deal if our expressions don't match 100% of the Intel manual as long as we keep the good semantics of instructions.

Regarding the overflow flag of `ROL`, our pseudo code is:

```
if (count & countmask == 1):
    of ← msb(dst) xor cf;
else:
    of ← of;
```

**Comment by gyorokpeter** [comment]
Thanks. I guess I'll have to work around this in user code then.

**Comment by JonathanSalwan** [comment]
> I'll have to work around this in user code then.

What do you need exactly?

**Comment by gyorokpeter** [comment]
I'm trying to do dead code elimination by checking what registers each instruction reads and writes. But this odd behavior of ROL causes the instruction before it that sets CF/OF to be considered "alive" since the ROL will allegedly use those values. Even if the rotation count is a fixed constant other than 0. So I have to change my analysing code to remove CF and OF from the read registers if the instruction is a ROL.
