### ISSUE TITLE
node.evaluate(n) -> returns n possible evaluations according to symvar in node

### ISSUE THREAD

**Issue by bannsec** [JonathanSalwan/Triton#570]
I'm looking at an AST node like the following:

```python
((_ extract 63 0) ((_ zero_extend 0) (ite (= (bvor (bvxor ((_ extract 0 0) ((_ extract 31 31) (bvsub ((_ extract 31 0) ((_ zero_extend 56) SymVar_0)) ((_ sign_extend 24) (_ bv4 8))))) ((_ extract 0 0) ((_ extract 31 31) (bvand (bvxor ((_ extract 31 0) ((_ zero_extend 56) SymVar_0)) ((_ sign_extend 24) (_ bv4 8))) (bvxor ((_ extract 31 0) ((_ zero_extend 56) SymVar_0)) ((_ extract 31 0) (bvsub ((_ extract 31 0) ((_ zero_extend 56) SymVar_0)) ((_ sign_extend 24) (_ bv4 8))))))))) ((_ extract 0 0) (ite (= ((_ extract 31 0) (bvsub ((_ extract 31 0) ((_ zero_extend 56) SymVar_0)) ((_ sign_extend 24) (_ bv4 8)))) (_ bv0 32)) (_ bv1 1) (_ bv0 1)))) (_ bv1 1)) (_ bv20 64) (_ bv5 64))))
```

I happen to know there are two valid solutions for this, namely `20` and `5`. How do I go about efficiently asking Triton to enumerate those values for me from the above AST node?

**Comment by Owlz** [comment]
I should say that I have tried the solution posted here:

https://stackoverflow.com/questions/13395391/z3-finding-all-satisfying-models

While that works, it is incredibly slow. This is primarily because it appears Triton's z3 solver instance loses state between independent `getModel` calls. This causes z3 to have to re-do all the previous work plus the new constraint each time.

Utilizing the Triton `getModels` call does not do what I intended in this case, since there are many models that, in the above example, come back as `5`. I only care about the unique models for a specific variable (in this case, the pseudo-variable that I assign to this expression).

**Comment by JonathanSalwan** [comment]
> https://stackoverflow.com/questions/13395391/z3-finding-all-satisfying-models

This is actually what `getModels` does. The code can be found [here](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/engines/solver/solverEngine.cpp#L183-L190).

**Comment by Owlz** [comment]
So if I understand `getModels` correctly, it will do that process without care for specific unique outputs. I.e.: it will get multiple possible models, even if they evaluate to the same output. This happens when the input variables have unused portions. For example, the ast evaluation is only dependent on the first byte of a multi-byte symbolic variable, the top bytes could be anything, and not actually change the output.

In the example above, the results I'm getting from `getModels` is effectively:
```python
[5, 5, 5, 5, 5, 20, 20, 20, 20, 20, 20, 20]
```

I am not claiming those are invalid models are values, however the redundancy of them is problematic in my case since, among other things, z3 is wasting cycles enumerating something again. The output I would want is simply:
```python
[5,20]
```

It's a subtle difference between getting multiple models for a given set of statements (which `getModels` indeed does), and getting unique outputs for the statement itself.

**Comment by JonathanSalwan** [comment]
Mmmmmh, can you provide a small PoC in a python script? Because, if i'm understanding correctly your point, we should get `[5,20]` as a result and not ` [5, 5, 5, 5, 5, 20, 20, 20, 20, 20, 20, 20]`.

**Comment by Owlz** [comment]
Right. So the code I've been working with is all wrapped up in larissa right now. However, the pseudo-code for what I'm doing follows.

1. Make eax symbolic
1. Compute instruction to compare eax with 4
1. Compute instruction to jle to some address
1. Check what valid addresses for RIP are now.

While this is for `rip` in this example, the same question would be asked for other vars/regs:

```python
# Make eax symbolic
state.ctx.convertRegisterToSymbolicVariable(state.ctx.Register(triton.REG.X86_64.EAX))

# cmp eax, 4
inst = triton.Instruction()
inst.setAddress(0)
inst.setOpcodes('\x83\xf8\x04')
state.ctx.processing(inst)

# jle    0x14
inst = triton.Instruction()
inst.setAddress(0)
inst.setOpcodes("\x7E\x12")
state.ctx.processing(inst)

# Build rip
rip = state.ctx.getFullAst(state.ctx.buildSymbolicRegister(state.ctx.Register(triton.REG.X86_64.RIP)))

# Attempt to enumerate possible values of rip
ast_ctx = state.ctx.getAstContext()
whip = state.se._get_whip(64)
whip_var = ast_ctx.variable(whip)
state.ctx.getModels(ast_ctx.assert_(whip_var == rip),12)
```

The output models are likely valid, but in my case I'm attempting to enumerate only the different values for the ast as a whole, of which many of the different models produce the same ast value output.

**Comment by JonathanSalwan** [comment]
Indeed, Triton doesn't provide unique models for each variable. We will don't provide such thing implicitly. The best way to do this is to call a second time `getModel` without values of last the models and repeat this operation until their is no model available.

**Comment by Owlz** [comment]
While that method works (i have implemented it previously in Triton), it renders performing those queries time and computationally intensive to the point where it's infeasible to use Triton. The root problem for symbolic evaluation in that manner isn't the infeasible part, just the API exposure limitations.

Can we make that an API call? For instance, change `variable.evaluate()` to add an optional `n` param to return `n` possible evaluations?

**Comment by JonathanSalwan** [comment]
Mmmmh, let me few days to think about it.

**Comment by JonathanSalwan** [comment]
closing this
