### ISSUE TITLE
Is triton compatible with pypy?

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#593]
Hi I want to use triton with pypy, and set up  a virtual environment using pypy as the interpreter. After compiling and install triton in the virtual environment, I execute `import triton`. But it reports that `ImportError: No module named triton`.  However I can find `triton.so` in the `site-packages` directory in the environment. 

If I do not use `pypy` as the default interpreter in the virtual environment, `import triton` succeeds.
My question is how to solve this problem and thanks very much.

**Comment by JonathanSalwan** [comment]
I don't know, i'm not comfortable with pypy env. Feel free to close it if you succeed.

**Comment by JonathanSalwan** [comment]
Is it ok? Can I close it?

**Comment by vancaho** [comment]
Not ok right now...

**Comment by kenoph** [comment]
I'll try to compile triton with pypy, but I just want to mention that triton seems to work very well with cython/pyximport.

Basically you just need to create a launcher script:

```python
#!/usr/bin/env triton

import pyximport; pyximport.install()
import main      # imports main.pyx

main.main()
```

This gives me a pretty nice speedup. I didn't do benchmarks because I don't want to spend time on that, but it's obvious from the output speed of my script.

Of course you can also cythonize everything at the beginning, but I find the `pyximport` way to be easier and faster to use.

**Comment by JonathanSalwan** [comment]
awesome.

> I'll try to compile triton with pypy,

woot, keep me in touch that i can close this thread then :)

**Comment by kenoph** [comment]
Hey, just as an update, I looked into it and it looks like pypy requires more effort than I can put in at the moment. I would recommend people to use cython for the time being, as it seems to work very well and it gives a nice speedup (while keeping pretty much all of python's benefits).

I might come back to it if I need to make my tool faster, but so far the bottleneck has been the cpp code anyway.

**Comment by JonathanSalwan** [comment]
I'm closing this for now. Feel free to reopen it if someone want to add the `pypy` support.
