### ISSUE TITLE
XOR a register with itself does not clear taint

### ISSUE THREAD

**Issue by douggard** [JonathanSalwan/Triton#643]
I think this might be because of the over approximation approach. I don't know if there is any special case handling for instructions, but this would be nice to have.

```c++
int main(int ac, const char **av) {
	triton::API api;
	api.setArchitecture(triton::arch::ARCH_X86_64);
	api.taintRegister(api.getRegister(triton::arch::ID_REG_RAX));

	std::cout << api.isRegisterTainted(api.getRegister(triton::arch::ID_REG_RAX)) << std::endl;

	BYTE insn[3] = { 0x48, 0x31, 0xc0 };
	triton::arch::Instruction inst;
	inst.setOpcode(insn, 3);
	api.processing(inst);

	std::cout << api.isRegisterTainted(api.getRegister(triton::arch::ID_REG_RAX)) << std::endl;

	return 0;
}
```

```
1
1
```

**Comment by JonathanSalwan** [comment]
Why should we clear the taint?

**Comment by douggard** [comment]
On a full width register it is the equivalent of `mov reg, 0`. Moving an immediate into a register negates any control one has over it. It is no longer tainted by the original data.

**Comment by JonathanSalwan** [comment]
I'm not agree with this. Result values and taint spread are two distinct things. A `XOR` does an union of two sources whatever the value or its origin. Now if you want to know what values can hold a register (let's say `RAX` from your example) after executing the `XOR` instruction, you should use the symbolic representation and ask for a model (result will be 0). Tainting is not used to determine what range of values an instruction's operands can hold.

By definition a Taint Analysis is used to determine what instructions use a specific area (regs and cells mem). Let's use an example:

```
1. mov rax, [tainted_area]
2. xor rax, rax
3. inc rax
```

In this example all instructions use a register which comes from a tainted area even if at the third instruction the value can only be equal to 1. Now, if the question is "*What values can hold the rax register at the third instruction? (because I know it's user dependent)*, the answer must be provided by the symbolic engine and not the taint engine.

**Comment by douggard** [comment]
Thanks! I still disagree, but I see the definition you are using which helps me work with Triton. My definition is probably a little less rigorous and pure. 

I think of it more as which registers the data affects. So if `tainted_area` has no effect on `rax` after an `xor`, it is no longer tainted. The tainted data doesn't influence the value in `rax` at `3` at all.

**Comment by JonathanSalwan** [comment]
I got your point. I think it's just a point of view regarding the preciseness of the taint analysis.
