### ISSUE TITLE
Get Z3 expression from the python side

### ISSUE THREAD

**Issue by thebabush** [JonathanSalwan/Triton#651]
Hi again,

I'm trying to get a Z3 expression out of a Triton AstNode. I know I can do it from C++, but for now I'm prototyping so I would like to keep as much as possible in python.

I couldn't find anything in the docs, so I went ahead and wrote [a small wrapper](https://github.com/kenoph/thelp) using ctypes (leveraging Z3 python bindings).

I tried to do everything in a custom method inside pyTritonContext, but there's some problem I can't figure out while creating a python `z3.Ast` object :/
It's kind of hacky because I'm building a ctype object from C++, but if you think it could be useful I can try to fix what's wrong and submit a pull request. Otherwise, I'll just stick to my ctypes wrapper.

Thanks

**Comment by JonathanSalwan** [comment]
Could be interesting to have this kind of feature directly into the `libTriton` but i don't know how to do it due to the fact that `libz3` does not exposes its python bindings directly into their lib. I'm not really conformable with the idea to split the API into several files (`.so` and `.py`). I would like to keep everything into a `.so` which is more standalone. If you manage to integrate this method into the `libTriton`, i will be more than happy to merge it into `dev-v0.6`.

**Comment by kenoph** [comment]
#653
