### ISSUE TITLE
Remove template declaration

### ISSUE THREAD

**Issue by illera88** [JonathanSalwan/Triton#686]
What is the point of having this if it is not implemented anywhere: 
https://github.com/JonathanSalwan/Triton/blob/b51a4e8909aa7fb86366962467795122a7da2387/src/libtriton/includes/triton/coreUtils.hpp#L39
?

Cheers

**Comment by JonathanSalwan** [comment]
[x8664Cpu](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x8664Cpu.cpp#L692-L757) and [x86Cpu](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Cpu.cpp#L520-L536) :)

**Comment by dhcerpa** [comment]
Hi Jonathan, I have helped @illera88 in the past with multiple compiler issues in Triton. IMO it is bad practice to have a template declaration without a definition just for the sake of having some specializations. @illera88 was having a linker error yesterday because he was using the template which is declared but not defined. What's the point of having a template if you are not going to have a generic implementation? You may as well just have 3 overloads of the same function for the 3 types that you need, which is essentially, what you have.  This is why I told him to report the issue, there is really no point in having that template function and it is confusing for library users.

Hope this helps!

**Comment by JonathanSalwan** [comment]
> You may as well just have 3 overloads of the same function for the 3 types that you need, which is essentially, what you have. 

mmmh, let discuss about it:

```cpp
triton::uint512 value = triton::utils::fromBufferToUint<triton::uint256>(this->ymm4);
```

```value``` is a uint512 for every registers. The argument to ```fromBufferToUint``` is a pointer. How can I know what is the size of the register only from the pointer? If I overload 3 the types like this:

```cpp
uint128 fromBufferToUint(const triton::uint8* buffer);
uint256 fromBufferToUint(const triton::uint8* buffer);
uint512 fromBufferToUint(const triton::uint8* buffer);
``` 

the following code will result into an invalid read:

```cpp
triton::uint512 value = triton::utils::fromBufferToUint(this->xmm1); /* xmm1 is 128-bits size */
```

right?

**Comment by dhcerpa** [comment]
@JonathanSalwan Ok, I see what you want to do there and I guess it is a matter of preference. While the code is correct, you are using the template language feature to overcome the limitation of not being able to override functions based on return type. 

I still find weird that you have a template declaration without definition and some people, like @illera88 did, may try to use it and find linker errors. Personally I'd rather just have 3 functions with different names rather than a template since there was never the intention of having an actual generic implementation of the function. Only the 3 specializations exist and in the call you have to specify the template parameter type anyway because the compiler can't infer it so you may as well just call the different functions.

Just my opinion of course :). Thanks for the discussion!

**Comment by JonathanSalwan** [comment]
it's interesting and you're right on some points. Let me few days to think about it.

**Comment by pbrunet** [comment]
What about having these specialisation like we do now and the generic
implementation raising a static_assert error? It would give the correct
information without link time issue.

2018-06-06 11:01 GMT+02:00 Jonathan Salwan <notifications@github.com>:

**Comment by dhcerpa** [comment]
That could be a good solution too. With a nice friendly message the user
would know that it can't use the template with any type but just those
supported, instead of having to decipher a super long linker error
