### ISSUE TITLE
bvror/bvrol usage

### ISSUE THREAD

**Issue by TehRick** [JonathanSalwan/Triton#751]
Hey, sorry to bother again but it is a quick question.
In x86Semantics, I noticed that for a lot (maybe all) of bvror and bvrol the rot count is evaluated.
Then I saw that BvrorNode expects a DECIMAL_NODE and I wonder why ?
Thanks

**Comment by JonathanSalwan** [comment]
In fact it's not a design choice but a limitation of the SMT2-Lib. According to the [QF_BV specification](http://smtlib.cs.uiowa.edu/Logics/QF_BV.smt2), Triton's rotate terms (`bvrol` and `bvror`) cannot have a symbolic index of rotation.

```smt
((_ rotate_left i) (_ BitVec m) (_ BitVec m))
; ((_ rotate_left i) x) means rotate bits of x to the left i times

((_ rotate_right i) (_ BitVec m) (_ BitVec m))
; ((_ rotate_right i) x) means rotate bits of x to the right i times
```

So, I'm very surprised that Z3's allows it. I know that Z3 extends the SMT2-Lib specification to support advanced terms but we cannot provide terms which are not supported by the SMT2-Lib otherwise it will stuck us to only use Z3 as solver.

I also know that a rotation can be performed with a bitwise operation like we do for the [emulation part](https://github.com/JonathanSalwan/Triton/blob/9c5c39e79925b9ef0ace85a10598564126d8d95f/src/libtriton/ast/ast.cpp#L722). Maybe that's how Z3 handles the trick...

However you have noted an interesting point: _Z3 supports symbolic index rotation_, so why not us too?

So, what I suggest:

* Add a new mode: `SYMBOLIZE_INDEX_ROTATION`
* Modify  `bvrol` and `bvror` functions to take in account this mode and using bitwise operations if the mode is enabled.

**Comment by JonathanSalwan** [comment]
Also, the function prototype of `bvror` and `bvrol` were weird. So we swapped operands from `bvrol(rot, expr)` to `bvrol(expr, rot)` in order to be homogeneous with other shift operators.

**Comment by JonathanSalwan** [comment]
Should be ok now :)
