### ISSUE TITLE
Question about deal with PE file 

### ISSUE THREAD

**Issue by sanxianxian** [JonathanSalwan/Triton#765]
Hi,
 I want to use Triton on Windows and I have some questions about libTriton.
 I want to analyze(such as taint analysis) the pe file(simple) by triton.I see you mentioned the libTriton takes opcodes as inputs ,and in other issue mentioned triton had added support for pe file format,does it means that I can use libtriton on python to take pe file as input?  
and if it dose how should I do?because i only find an example of python named small_x86-64_symbolic_emulator,and it takes the elf file format as input.So I read the document of lief,but it's hard for me.So I wonder if it‘s accessiable.
thank you for answering!

**Comment by JonathanSalwan** [comment]
Hey,

Triton takes as input one instruction. Repeating this operation several times means that you simulate a trace execution (that's why Triton is a dynamic binary analysis framework).

Triton is very a powerful tool but need to be customized, it's not a a turnkey tool. If you want to analyze traces over a whole program without dealing with external functions etc, I really recommend to combine Triton with a DBI tool. Otherwise, the `small_x86-64_symbolic_emulator` example is the only way to emulate a program.

**Comment by sanxianxian** [comment]
So if i only  want simulate one trace of PE file by triton on windows, i should use DBI tool to get instructions of the trace,then use triton to processing each instruction,is it right?I don't know if I got it.

**Comment by JonathanSalwan** [comment]
Yes, that's right.
