### ISSUE TITLE
Question about ctx.processing(inst) and ctx.setConcreteRegisterValue()

### ISSUE THREAD

**Issue by SoonwonPark** [JonathanSalwan/Triton#771]
I have a question about ctx.processing(inst) and ctx.setConcreteRegisterValue().

Can ctx.setConcreteRegisterValue() change the value of a specific register? If so, and I think so, can ctx.processing(inst) handle the modified value of the register?

For example, there is an instruction "jmp     dword ptr ds:off_412D54[edx_4]" at the address of 0x412BFF.

If I want to use different values for edx at 0x412BFF, is it possible to use ctx.setConcreteRegisterValue()?
And can ctx.processing(inst) handle different edx values?

Thank you.

**Comment by JonathanSalwan** [comment]
Triton deals with two states. The concrete one and the symbolic one. If there is no entry (reg or mem) in the symbolic state, Triton will get the concrete value from the concrete state and update the symbolic state with this concrete value. Otherwise, if there were an entry in the symbolic state, Triton will choose this entry instead of the one from the concrete state and will update the concrete state to be synchronized with the symbolic one.

For example, when you set a concrete value with `setConcreteRegisterValue(rax)` and if there is already an entry for `rax` in the symbolic state, Triton will choose the expression of `rax` in the symbolic state and overwrite your concrete value with the new state provided by `processing`. It means that your `setConcreteRegisterValue(rax)` have no effect. If you want to force Triton to use the concrete value and not the symbolic one at the next `processing` you have to concretize the register. For example:

```python
ctx.setConcreteRegisterValue(rax) 
ctx.concretizeRegister(rax) # Remove the entry of rax in the symbolic state. It will force Triton to use the concrete state at the next read of rax.
ctx.processing("mov rbx, rax") # Triton will check if rax is an entry of the symbolic state. In this case no because of the concretizeRegister, so Triton will choose the concrete value.
```
