### ISSUE TITLE
Question about python api

### ISSUE THREAD

**Issue by sanxianxian** [JonathanSalwan/Triton#773]
hello,i have a question on python api.
How can i use function "setDisassembly (const std::string &str)" in python? Is it only used in c++?
I use it like “setOpcode” but failed.

**Comment by JonathanSalwan** [comment]
We don't want to expose this API in Python bindings because we consider it as internal method. Why do you need such feature? Can you provide a scenario example where you need it?

**Comment by sanxianxian** [comment]
Thanks for replying!
Because i want to input a trace extracted  by PIN，but i have't found how to extract the trace in opcode form.I can only get disassembly trace.So i think if i can use this API instead of "setOpcode" to process the disassembly trace like in the example forward_tainting.py .
Is it feasible？

**Comment by JonathanSalwan** [comment]
Why are you not using our pintool module? Triton takes as input the `opcode`, if you only set its disassembly it will not work. If you don't want to use our pintool, [see](https://github.com/JonathanSalwan/Triton/blob/e49330e14c28bccd1d5dea3ccbcd6d0d09220938/src/tracer/pin/main.cpp#L233) how we defined opcode to a Triton's instruction. If you want to use our pintool you have to compile Triton with `cmake -DPINTOOL=on` flag. We really recommend to use our pintool because we used a lot of tricks to synchronize Pin and Triton states.

**Comment by sanxianxian** [comment]
I want use triton pintools originally,  but i'm unacquainted to linux system, So i firstly try to use PIN on windows .But it seems not feasible..If my works don't have a deadline ,i would like to use triton pintools surely...
If i can't find a way to solve the problem,i will try to use the pintools :)
