### ISSUE TITLE
Exploring all switch case targets (python)

### ISSUE THREAD

**Issue by kokole** [JonathanSalwan/Triton#802]
How can I do this? The code looks something like this (from obfuscated binary):
```
    mov       rcx, [jump_index]
    and       ecx, 0Fh
    mov       [rbp+60h], rcx
    mov       rax, [rbp+60h]
    cmp       rax, 0Eh
    push      rax
    mov rax,  default_case
    mov       rbx, switch_jump
    cmova     rbx, rax
    pop       rax
    push      rbx
    retn       <- conditional jump
switch_jump:
    mov       rdx, image_base
    mov       eax, [rdx+rax*4+switch_table_offset]
    add       rax, rdx
    jmp       rax
```

You can see that the switch targets are at (image_base + read_dword(image_base + switch_table_offset + index * 4)), where index is < 15 (because of the cmp + cmova instructions).

So how can I get this information with Triton without hardcoding any addresses? I've already tried a few things but I can't seem to get it to work. I should also say I'm new to symbolic execution.

Additional note: what I'm trying to do is remove obfuscation from a function with pattern matching, so I need to find all its code.

Thank you.

**Comment by PixelRick** [comment]
Pointers are concretized for memory accesses so your problem has no straightforward solution.
If you want the different possible values of rax it means you have to read the values in memory at the different addresses that 'rdx+rax*4+switch_table_offset' can have.
What I would do is have the index symbolized so that you can then detect a symbolized LEA in the memory load access (instruction.getLoadAccess()) of the mov here and then check that its your identified variable. From there you can generate the possible values for each input index by changing the variable concrete value and accordingly evaluating the lea ast node to feed a ctx.getConcreteMemory(..) read manually.

**Comment by JonathanSalwan** [comment]
What @PixelRick said is a potential solution. A second potential solution could be:

```python
# current path constraint to reach this program point
pc = ctx.getPathConstraintsAst()

# The memory operand of your identified instruction. Here, the lea
# is the index of your switch case (rdx+rax*4+switch_table_offset).
# As PixelRick said, you have to symbolize the register corresponding
# to the index controlled by the user at the beginning of the execution. 
lea = mem.getLeaAst()

# Ask for 1000 solutions which satisfy the current path constraint and
# where you list all possible values of lea. 
m = ctx.getModels(ast.land([pc, lea >= 0]), 1000)

```
