### ISSUE TITLE
taint propagation wrong for "xor reg, reg"

### ISSUE THREAD

**Issue by Toizi** [JonathanSalwan/Triton#825]
As the title says, the taint propagation is wrong for `xor` if the source and destination register is the same. It should clear the taint since the result of the operation does not depend on the value of the tainted source/destination

Example:
```
eax is tainted
xor eax, eax  # this should clear the taint but it doesn't
eax is tainted
```

**Comment by JonathanSalwan** [comment]
Thing is that we don't reason about semantics spreading for taint rules (see #643).

**Comment by Toizi** [comment]
@JonathanSalwan  I guess I can follow your reasoning but this makes the taint analysis without symbolic execution rather useless, which is what I am using right now.

I don't see why going for the theoretically correct approach makes sense here since this is always used for `mov reg, 0` due to being shorter. It is basically a different instruction than `xor` and complicates the analysis for any user but I guess it is your decision in the end

**Comment by JonathanSalwan** [comment]
To be honest i was thinking about removing the taint engine, because as you said it's useless without the taint engine... A second option could be to improve the taint engine by making spread rules working at the bit level according to the instruction semantics. Thing is that the second option is a huge patch as we have to describe the taint propagation of each instruction (like for the sym engine). Without this kind of description we can not determine that a `xor rax, rax` is equal to a `mov rax, 0` or a `mul rax, 0`, or a `shl rax, 64` etc.

So, I really don't know what to do...
