### ISSUE TITLE
How to install Triton into Python for Windows

### ISSUE THREAD

**Issue by HuErr** [JonathanSalwan/Triton#839]
please.
I compiled Triton in windows.How to install Triton into Python for Windows

**Comment by JonathanSalwan** [comment]
You have to rename the `triton.dll` file into `triton.pyd` and put this `pyd` into your `PYTHONPATH`.

**Comment by cssaheel** [comment]
I successfully compiled triton.dll for windows and successfully ran backward_slicing.py on Windows. However I am trying to run other python scripts like this:
./build/triton ./src/examples/pin/runtime_memory_tainting.py ./src/samples/crackmes/crackme_xor a

the problem is that I don't have ./build/triton, please help. Thanks!
