### ISSUE TITLE
Do not build ASTs for nontainted instructions

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#888]
Hi!

We are implementing DynamoRIO tracer for Triton and setting the concrete values through callbacks. We also use `ONLY_ON_TAINTED` and `ONLY_ON_SYMBOLIZED`. But Triton is still building ASTs for nontainted instructions. Is there a way to skip building ASTs? If the answer is no, then how can I contribute to solve this problem?

I think that just skipping the processing of instructions with nontainted operands can break taint propagation.

P.S. Added a bad example in first edition of this message.

**Comment by SweetVishnya** [comment]
I am not able to give a correct counterexample. Now It seems to work. Won't it break anything in symbolic engine if we just skip processing instructions with nontainted operands?

**Comment by JonathanSalwan** [comment]
> But Triton is still building ASTs for nontainted instructions. Is there a way to skip building ASTs? 

Currently, the taint is applied in functions describing the instruction semantic (e.g `mov_s()`) and we also craft the AST of the instruction semantics in these functions.... 

> If the answer is no, then how can I contribute to solve this problem?

A solution could be to export the taint spreading outside these functions. But i don't know yet if i want this in Triton. Actually, there is some brainstorming on our side regarding the taint engine. For v0.9 we have two ideas:

Let consider the `MOV` instruction.

1. We apply the taint analysis on the AST itself in post execution instead of doing it in `mov_s`.
2. We apply the taint analysis for each instruction but in another function than `mov_s`, for example let say `mov_t`.

The option 1 is more like an IR based framework but in this case you have to craft the AST. The option 2 would allows the user to apply a taint analysis without crafting the AST but in this case we have to describe the taint spreading for each instruction.

> Won't it break anything in symbolic engine if we just skip processing instructions with nontainted operands?

Mmmmh, if you keep a synch with DR of the concrete state and as the taint rules is over-approximated it should be ok but well, that's the theory :D.

**Comment by SweetVishnya** [comment]
IMHO, the second proposed solution is better. It is a common case for symbolic engines (especially for guided fuzzing and inverting branches, APEG) to perform a lightweight taint first. And then symbolically execute only tainted instructions.

> Mmmmh, if you keep a synch with DR of the concrete state and as the taint rules is over-approximated it should be ok but well, that's the theory :D.

And what about `popal` instruction which kills registers but have no operands?

**Comment by SweetVishnya** [comment]
> It is a common case for symbolic engines (especially for guided fuzzing and inverting branches, APEG) to perform a lightweight taint first. And then symbolically execute only tainted instructions.

Of course you should somehow manage the concrete execution if you don't have a tracer. But lots of deverging emulation engines can make a mess, like in MIASM the have jitter and AST concrete execution.

**Comment by JonathanSalwan** [comment]
> And what about `popal` instruction which kills registers but have no operands?

Should be ok. Even if there is no operand, your callbacks like `GET_CONCRETE_{MEMORY, REGISTER}_VALUE` should be called and if the memory area is tainted, popped items should be kept symbolic.

**Comment by SweetVishnya** [comment]
I meant the other case. Let `eax` be symbolic and no memory is symbolic. Then `popal` should make `eax` non-symbolic. It's memory operands are not tainted, so I skip processing the `popal` and `eax` keeps wrongly symbolic.

**Comment by JonathanSalwan** [comment]
Mmmh, indeed I think there is an issue with every implicit behavior like you mentioned.

**Comment by JonathanSalwan** [comment]
In fact, at each program point you should test if your concrete state is still synch with your symbolic one and re-synch if necessary (which will kill the symbolic reasoning) but this solution does not scale at all I guess.

**Comment by SweetVishnya** [comment]
I thought about supporting some kind of white list of instructions to always process.

**Comment by crackzhazha** [comment]
where is  your DynamoRIO tracer for Triton,I also want to contribute to the work for DynamoRIO support
